# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:
  db-server:
    image: postgres:latest
    container_name: db-server
    ports:
      - "5432:5432"
    networks:
      - localdev
    environment:
      - POSTGRES_USER=app_user # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=myHardCoreDevDb123 # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=InstitutionalDb # The PostgreSQL default database (automatically created at first launch)
  institutional-api:
    build:
      context: .
      dockerfile: src/Institutional.Api/Dockerfile
    image: institutional-api:local
    container_name: institutional-api
    depends_on:
      - db-server
    networks:
      - localdev

volumes:
  sqlvolume: